services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
    networks:
      - recycle-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models  # Mount models directory for ML model
    environment:
      - PYTHONPATH=/app
    networks:
      - recycle-app-network

networks:
  recycle-app-network:
    driver: bridge 